image: google/cloud-sdk:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  BACKEND_IMAGE: awesome-cats-backend
  FRONTEND_IMAGE: awesome-cats-frontend
  REPO_URI_BACKEND: gcr.io/$GCP_PROJECT_ID/$BACKEND_IMAGE
  REPO_URI_FRONTEND: gcr.io/$GCP_PROJECT_ID/$FRONTEND_IMAGE
  TAG: latest
  TAG_BACKEND: $REPO_URI_BACKEND:$TAG
  TAG_FRONTEND: $REPO_URI_FRONTEND:$TAG
  HELM_VERSION: "v3.14.0"

stages:
  - plan
  - apply
  - destroy
  - build-push
  - create-table
  - helm-install
  - apply-applications
  - install-argocd
  - cert-manager
  - new-ingress

.hidden-terraform-job:
  image:
    name: ubuntu:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

  before_script:
    - apt-get update && apt-get install -y curl unzip jq
    - curl -fsSL https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)_linux_amd64.zip -o terraform.zip
    - unzip terraform.zip
    - mv terraform /usr/local/bin/
    - apt-get update && apt-get install -y curl 
    - export GOOGLE_APPLICATION_CREDENTIALS=$CI_PROJECT_DIR/terraform-key.json
    - echo "$GOOGLE_CREDENTIALS" > "$GOOGLE_APPLICATION_CREDENTIALS"
    - rm -rf .terraform
    - cd Terraform
    - terraform -v
    - |
      cat > backend.tf <<EOF
      terraform {
        backend "gcs" {
          bucket  = "BUCKET-NAME"
          prefix  = "tfstate"
        }
      }
      EOF
    - terraform init -reconfigure
    - curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl" && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    # Install gke-gcloud-auth-plugin
    - export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    - kubectl version --client

# Terraform plan job
plan:
  extends: .hidden-terraform-job
  stage: plan
  script:
    - terraform plan -out=tfplan
  when: always

# Terraform apply job
apply:
  extends: .hidden-terraform-job
  stage: apply
  script:
    - terraform apply -auto-approve
  when: manual

# Terraform destroy job
destroy:
  extends: .hidden-terraform-job
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual


.docker-rule:
  services:
  - name: docker:dind
  before_script:
    # Install Docker
    - apt-get update && apt-get install -y docker.io
    # Authenticate with Google Cloud
    - echo $GOOGLE_CREDENTIALS > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker --quiet

build-push-docker-images:
  extends: .docker-rule
  stage: build-push
  script: 
    # Build and push the first Docker image
    - docker build -t $TAG_BACKEND -f Docker/awesome_cats_backend/Dockerfile Docker/awesome_cats_backend/
    - docker push $TAG_BACKEND
    # Build and push the second Docker image
    - docker build -t $TAG_FRONTEND -f Docker/awesome_cats_frontend/Dockerfile Docker/awesome_cats_frontend/
    - docker push $TAG_FRONTEND
  when: manual


.connect-gke:
  image:
    name: google/cloud-sdk:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - export GOOGLE_APPLICATION_CREDENTIALS=$CI_PROJECT_DIR/key.json
    - echo "$GOOGLE_CREDENTIALS" > "$GOOGLE_APPLICATION_CREDENTIALS"
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials bermet --zone $GCP_ZONE --project $GCP_PROJECT_ID
    - kubectl get nodes


create_table:
  extends: .connect-gke
  stage: create-table
  script:
    - apt-get install -y postgresql postgresql-contrib
    - cd Terraform 
    - export PGPASSWORD=$PGPASSWORD
    - echo "Creating tables..."
    - psql -h $PGHOST -p 5432 -U $PGUSER -d $PGDATABASE -f ./modules/database/create-tables.sql
    - kubectl create secret generic db-credentials --from-literal=database=$PGDATABASE --from-literal=hostname=$PGHOST --from-literal=password=$PGPASSWORD --from-literal=username=$PGUSER 
  when: manual

configuring_helm:
  extends: .connect-gke
  stage: helm-install
  script:
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - helm version
    - helm repo update
    - kubectl create secret generic external-dns-gcp --from-file=credentials.json=$CI_PROJECT_DIR/key.json
    - helm version
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts    
    - helm install my-nginx-ingress ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
    - helm upgrade --install external-dns bitnami/external-dns --set provider=google --set google.project=$GCP_PROJECT_ID --set google.serviceAccountSecret=external-dns-gcp --set txtOwnerId="api" --set policy=sync
    - kubectl create ns monitoring
    - kubectl create secret generic db-credentials --from-literal=database=$PGDATABASE --from-literal=hostname=$PGHOST --from-literal=password=$PGPASSWORD --from-literal=username=$PGUSER -n monitoring
    # - kubectl rollout status -n argocd deployment/argocd-server
    - helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheus.prometheusSpec.serviceMonitorSelector.matchLabels.release=prometheus
    - helm install postgres-exporter prometheus-community/prometheus-postgres-exporter --namespace monitoring --set postgresUser=$PGUSER --set postgresPassword=$PGPASSWORD --set postgresDatabase=postgres  --set postgresHost=$PGHOST --set serviceMonitor.enabled=true --set serviceMonitor.selector.release=prometheus --set prometheus.prometheusSpec.serviceMonitorSelector.matchLabels.release=prometheus
    - until kubectl get svc -n monitoring postgres-exporter-prometheus-postgres-exporter; do echo "Waiting for postgres-exporter-prometheus-postgres-exporter service..."; sleep 10; done
    - export POSTGRES_EXPORTER_IP=$(kubectl get svc -n monitoring postgres-exporter-prometheus-postgres-exporter -o jsonpath='{.spec.clusterIP}')
    - echo $POSTGRES_EXPORTER_IP > postgres_exporter_ip.txt
    - helm install stackdriver-exporter prometheus-community/prometheus-stackdriver-exporter --namespace monitoring --set stackdriver.projectId=$PROJECT_ID --set prometheus.prometheusSpec.serviceMonitorSelector.matchLabels.release=prometheus
    - helm upgrade prometheus prometheus-community/kube-prometheus-stack -f ./values.yml -n monitoring --set postgresExporterIp=$POSTGRES_EXPORTER_IP
  artifacts:
    paths:
      - postgres_exporter_ip.txt
  when: manual

apply-applications:
  extends: .connect-gke
  stage: apply-applications
  script: 
    - kubectl apply -f ./Kubernetes/deployment.yaml
    - kubectl apply -f ./Kubernetes/service.yaml
    - kubectl apply -f ./Kubernetes/ingress.yaml
  when: manual

install-argocd:
  extends: .connect-gke
  stage: install-argocd
  script:
    - curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.7.8/argocd-linux-amd64
    - chmod +x ./argocd-linux-amd64
    - mv ./argocd-linux-amd64 /usr/local/bin/argocd
    - kubectl create namespace argocd
    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - sleep 10
    - kubectl port-forward -n argocd svc/argocd-server 8080:443 &
    - sleep 10
    # - kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
    - argocd admin initial-password -n argocd
    # - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  when: manual


cert-manager:
  extends: .connect-gke
  stage: cert-manager
  script:
    - curl -sSL https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -o helm.tar.gz
    - tar -zxvf helm.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm  
    - helm repo add jetstack https://charts.jetstack.io
    - kubectl create namespace cert-manager
    - helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --set installCRDs=true
    - kubectl apply -f ./Kubernetes/clusterissuer.yaml
    - sleep 20
    - kubectl apply -f ./Kubernetes/certificate.yaml
  when: manual

new-ingress:
  extends: .connect-gke
  stage: new-ingress
  script:
    - kubectl apply -f ./Kubernetes/NEWingress.yaml
  when: manual