config:
  datasource:
    host: YOUR-DATABASE-INSTANCE-IP 
    user: postgres
    password: postgres
    database: postgres

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'postgres_exporter'
        static_configs:
          - targets: ['{{ .Values.postgresExporterIp }}:80']

   
additionalPrometheusRulesMap:
  custom-alerts:
    groups:
      - name: CustomTestAlerts
        rules:
          - alert: TestAlertWarning
            expr: up == 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Test Alert: Service Down (instance {{ $labels.instance }})"
              description: "Service is down (up == 0)\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
          - alert: DiskSpaceWarning
            expr: (node_filesystem_avail_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"}) * 100 < 20
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Disk Space Warning (instance {{ $labels.instance }})"
              description: "Disk space is running low (< 20%)\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
          - alert: NodeCpuUsageHigh
            expr: rate(node_cpu_seconds_total[1m]) > 0.9
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "High CPU Usage on Node {{ $labels.instance }}"
              description: "Node {{ $labels.instance }} is experiencing high CPU usage: {{ $value }}%"

alertmanager:
  config:
    global:
      slack_api_url: "YOUR-SLACK-WEBHOOK"
    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - matchers:
            - severity=critical
          receiver: slack-general
        - matchers:
            - severity=warning
          receiver: slack-general

    receivers:
      - name: slack-general
        slack_configs:
          - channel: 'slack-channel'
            text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n\n{{ end }}"
